### ISSUE TITLE
I want device lock state how can i do that

### ISSUE THREAD

**Issue by AdnanKazi** [chihimng/flutter_is_lock_screen#1]
Hi i want feature like when users phone unlock i need to do some stuff but by using your plugin i cant differentiate between lock and inactive state i mean when i minimize app then it also do same thing so is it possible to implement to detect lock/unlock state.

Thank you

**Comment by elise-ng** [comment]
You will need to add your own logic to observe the state changes, and your target state transition will be from `AppLifecycleState.inactive && isLockScreen` to `AppLifecycleState.resumed`.

The aim of this plugin is only to provide a way to determine whether the app entered `AppLifecycleState.inactive` state due to screen locking or user dismissal.

Closing this due to out of scope feature request.
